------- CREATION DE LA BDD mini_ecommerce ------- 
CREATE DATABASE IF NOT EXISTS mini_ecommerce;

USE mini_ecommerce;

------- CREATION DES TABLES ------- 
---CREATION DE LA TABLE USER
CREATE TABLE USER (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(25) NOT NULL,
    prenom VARCHAR(25)NOT NULL,
    pseudo VARCHAR(100),
    email VARCHAR(150) NOT NULL UNIQUE,
    pwd TEXT NOT NULL
);

---CREATION DE LA TABLE PRODUCT
CREATE TABLE PRODUCT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nomProduct VARCHAR(25) NOT NULL,
    description TEXT,
    prix FLOAT NOT NULL,
    image VARCHAR(255) NULL,
    vendeur INT NULL
);

---CREATION DE LA TABLE ORDER
CREATE TABLE COMMANDE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    productID INT,
    userID INT,
    CONSTRAINT FK_Product FOREIGN KEY(productID) REFERENCES PRODUCT(id),
    CONSTRAINT FK_User FOREIGN KEY(userID) REFERENCES USER(id)
);

SHOW TABLES

------- AFFICHER LES ELEMENTS DANS UNE TABLE -------
SELECT * FROM USER;